[font]
size = 16.0

[font.bold]
family = "Monofur Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Monofur Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Monofur Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Monofur Nerd Font"
style = "Regular"

[general]
import = [
    "~/dotfiles/alacritty/.config/alacritty/themes/_current.toml"
]

[window]
decorations = "None"
padding = { x = 15 }
